services:
  dblae:
    build:
      context: .
      dockerfile: Dockerfile.builder
    image: dblae:latest
    container_name: dblae
    ports:
      - "5432:5432"
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
      - dblae_data:/var/lib/postgresql/data
    networks:
      - dblae_net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  dblae_data:
    name: dblae_data

networks:
  dblae_net:
    name: dblae_net
